### ISSUE TITLE
RuntimeException when building BillingClient

### ISSUE THREAD

**Issue by Nimade42** [googlesamples/android-play-billing#112]
Hello,

I have a crash that is growing very fast among my users. It seems that in some case a RuntimeException in thrown . I have not been able to find a pattern to reproduce but here is the stacktrace from Fabric:

`Fatal Exception: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
       at android.os.Handler.<init>(Handler.java:200)
       at android.os.Handler.<init>(Handler.java:114)
       at com.android.billingclient.api.BillingClientImpl.<init>(BillingClientImpl.java:83)
       at com.android.billingclient.api.BillingClient$Builder.build(BillingClient.java:157)
       at com.roularta.lib.managers.InAppPurchaseManager.setBillingClient(InAppPurchaseManager.java:59)
       at com.roularta.lib.managers.InAppPurchaseManager.getInstance(InAppPurchaseManager.java:71)
       at com.roularta.lib.webservices.services.ChService.execute(ChService.java:31)
       at com.roularta.lib.activities.LauncherActivity.startApp(LauncherActivity.java:434)
       at com.roularta.lib.activities.LauncherActivity.prepareAndStartApp(LauncherActivity.java:397)
       at com.roularta.lib.activities.LauncherActivity.access$200(LauncherActivity.java:71)
       at com.roularta.lib.activities.LauncherActivity$6.onAdClosed(LauncherActivity.java:369)
       at com.roularta.lib.managers.SmartAdManager.closeListener(SmartAdManager.java:108)
       at com.roularta.lib.managers.SmartAdManager.access$000(SmartAdManager.java:26)
       at com.roularta.lib.managers.SmartAdManager$1.adLoadingFailed(SmartAdManager.java:154)
       at com.smartadserver.android.library.SASInterstitialView$ProxyHandler.adLoadingFailed(SASInterstitialView.java:212)
       at com.smartadserver.android.library.controller.SASAdViewController$ProxyHandler.fail(SASAdViewController.java:297)
       at com.smartadserver.android.library.controller.SASAdViewController$ProxyHandler.adLoadingFailed(SASAdViewController.java:285)
       at com.smartadserver.android.library.provider.http.SASHttpAdElementProvider$AdElementResponseHandler.onFail(SASHttpAdElementProvider.java:171)
       at com.smartadserver.android.library.http.SASAsyncHttpClient$HttpRequestThread.run(SASAsyncHttpClient.java:346)

Stacktrace as a file: 
[com.roularta.lexpress_issue_3303_crash_5A329C4C01840001219B49EEDCA5F54A_397f2b45e0b411e7b16656847afe9799_0_v2.txt](https://github.com/googlesamples/android-play-billing/files/1558666/com.roularta.lexpress_issue_3303_crash_5A329C4C01840001219B49EEDCA5F54A_397f2b45e0b411e7b16656847afe9799_0_v2.txt)
`

**Comment by Chezlui** [comment]
Hi @Nimade42, 
Are you calling BillingClient from an activity? It looks like you are doing it from a Service. 
Not sure if it's your problem but you should call the BillingClient from inside your activity because the Handler has to be created in the UI Thread. Don't worry about performance because all the network calls are doing by the client in a different thread.

**Comment by Nimade42** [comment]
Hi @Chezlui 

I call BillingClient in a singleton, which is called from my activity. I pass the context of my activity to build the BillingClient so no no service and no threading from my part of the code (I was confident about the fact that Google had threaded what's needed to be)

**Comment by prachaya2** [comment]
active

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://issuetracker.google.com/issues/new?component=311487&template=1014446

Please reopen if you still think this is an issue with the sample.
