### ISSUE TITLE
TransactionTooLargeException on BillingClientImpl.startConnection

### ISSUE THREAD

**Issue by casolorz** [googlesamples/android-play-billing#132]
I've just started a staged rollout with the new billing api and already got one exception:

java.lang.RuntimeException: 
  at android.app.ApplicationPackageManager.queryIntentServicesAsUser (ApplicationPackageManager.java:605)
  at android.app.ApplicationPackageManager.queryIntentServices (ApplicationPackageManager.java:611)
  at com.android.billingclient.api.BillingClientImpl.startConnection (BillingClientImpl.java:219)

Caused by: android.os.TransactionTooLargeException: 
  at android.os.BinderProxy.transact (Native Method)
  at android.content.pm.IPackageManager$Stub$Proxy.queryIntentServices (IPackageManager.java:2328)
  at android.app.ApplicationPackageManager.queryIntentServicesAsUser (ApplicationPackageManager.java:599)

**Comment by cartland** [comment]
How often is the issue happening? This exception can be thrown even if nothing is wrong.
https://developer.android.com/reference/android/os/TransactionTooLargeException

**Comment by casolorz** [comment]
Doesn't seem like it has happened a lot, might have just been that one report.

**Comment by d-schmidt** [comment]
got hit by this today:

7.1.1 CPH1609
```
Caused by android.os.TransactionTooLargeException
       at android.os.BinderProxy.transact(Binder.java)
       at android.content.pm.IPackageManager$Stub$Proxy.queryIntentServices(IPackageManager.java:2287)
       at android.app.ApplicationPackageManager.queryIntentServicesAsUser(ApplicationPackageManager.java:572)
       at android.app.ApplicationPackageManager.queryIntentServices(ApplicationPackageManager.java:584)
       at com.android.billingclient.api.BillingClientImpl.startConnection(BillingClientImpl.java:219)
```

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".  Presently we are reserving Github for questions specifically about the samples so we can better serve you.
