### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState how to solve this

### ISSUE THREAD

**Issue by Prabha10cs** [googlesamples/android-play-billing#140]
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
        at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:223)
        at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:190)
        at biling_code.AcquireFragment.refreshUI(AcquireFragment.java:99)
        at com.example.Main_open.showRefreshedUi(Main_open.java:3009)
        at biling_code.MainViewController$UpdateListener.onPurchasesUpdated(MainViewController.java:183)
        at billing.BillingManager.onPurchasesUpdated(BillingManager.java:132)
        at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
        at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
        at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
        at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

**Comment by Fabi12345** [comment]
Try to wrap your commit(); into this:
if(!getSupportFragmentManager().isStateSaved()) {
    //your commit function
}

In my case it was: 
if(!getSupportFragmentManager().isStateSaved()) { 
                fragmentTransaction.remove(myFragment).commit();
}

It's a really shitty error, I was struggling with this a long time, Android should shame on this!

**Comment by Vale-polito** [comment]
col

**Comment by isaidamier** [comment]
Might you be able to follow the [TrivialDriveKotlin](https://github.com/googlesamples/android-play-billing/tree/master/TrivialDriveKotlin) sample so as to decouple your billing implementation from your activity lifecycle?

Apologies for the issues you are experiencing. In the future please post similar questions on StackOverflow. Presently we are reserving Github for questions specifically about the samples so we can better serve you.
