### ISSUE TITLE
Crash when using SKU android.test.canceled

### ISSUE THREAD

**Issue by nikz-dev** [googlesamples/android-play-billing#152]
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.example.billingmodule.billing.BillingManager.onPurchasesUpdated(BillingManager.java:170)
        at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
        at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
        at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
        at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7225)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by isaidamier** [comment]
Apologies for the issues you are experiencing. Presently we are reserving Github for questions specifically about the samples. Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library".
