### ISSUE TITLE
IInAppBillingService throws npe crash

### ISSUE THREAD

**Issue by laoli4121** [googlesamples/android-play-billing#173]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int com.android.vending.billing.IInAppBillingService.a(int, java.lang.String, java.lang.String)' on a null object reference
       at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection.onServiceConnected(BillingClientImpl.java:1012)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1264)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1281)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by ouchadam** [comment]
it looks like the latest version `1.2.2` internally catches all errors in `onServiceConnected` and treats it as a `disconnect`

**Comment by isaidamier** [comment]
Please file a ticket at https://issuetracker.google.com against component "Android Public Tracker > App Development > Google Play Billing Library"
