### ISSUE TITLE
IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by ertanden** [googlesamples/android-play-billing#28]
I get a lot of exceptions with the stack trace below. I guess we need to add a null check for mService in line IabHelper.java:330

```
Caused by java.lang.IllegalArgumentException: Service not registered: com.goseet.a.a.c@420bbdd0
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:954)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1566)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:484)
       at com.goseet.billing.util.IabHelper.dispose(IabHelper.java:330)
       at com.goseet.billing.util.IabHelper.disposeWhenFinished(IabHelper.java:350)
       at com.goseet.videowallpaper.InAppActivity.onDestroy(InAppActivity.java:39)
       at android.app.Activity.performDestroy(Activity.java:5400)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1112)
       at com.lbe.security.service.core.client.b.x.callActivityOnDestroy(Unknown Source)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3655)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3688)
       at android.app.ActivityThread.access$1200(ActivityThread.java:162)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5356)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by dandar3** [comment]
Did you get it by any chance on a device that doesn't have Google Play components installed? It just happened to me in that scenario.

Code does seem to check at line 330 for nulls in dispose(), it just that the service could not bind.

bindService() call in startSetup() should probably keep track on the boolean result and don't try to unbind if unsucesful - similar to this answer http://stackoverflow.com/a/8873328/308836

**Comment by xingstarx** [comment]
@dandar3 I thinks It is a good idea

**Comment by netomarin** [comment]
Hi
Because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.

Thanks.
