### ISSUE TITLE
What is [DF-RPC-01] error code?

### ISSUE THREAD

**Issue by songsingasong** [googlesamples/android-play-billing#48]
Hi,
I am currently developing "upgrading subscription item" function with "getBuyIntentToReplaceSkus()" method.
I query currently purchased items, and I put items' skus list as oldSkus parameter to 
>IabHelper.launchPurchaseFlow(Activity act, String sku, String itemType, List<String> oldSkus,
            int requestCode, OnIabPurchaseFinishedListener listener, String extraData).

I got the error from the google play service dialog says 
**"Error retrieving information from server. [DF-RPC-01]"**.

Also I got those logs.
```E/Parcel  (  948): Class not found when unmarshalling: com.google.android.finsky.billing.lightpurchase.PurchaseParams
E/Parcel  (  948): java.lang.ClassNotFoundException: com.google.android.finsky.billing.lightpurchase.PurchaseParams
E/Parcel  (  948): 	at java.lang.Class.classForName(Native Method)
E/Parcel  (  948): 	at java.lang.Class.forName(Class.java:308)
E/Parcel  (  948): 	at java.lang.Class.forName(Class.java:272)
E/Parcel  (  948): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
E/Parcel  (  948): 	at android.os.Parcel.readParcelable(Parcel.java:2239)
E/Parcel  (  948): 	at android.os.Parcel.readValue(Parcel.java:2146)
E/Parcel  (  948): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
E/Parcel  (  948): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
E/Parcel  (  948): 	at android.os.BaseBundle.getString(BaseBundle.java:918)
E/Parcel  (  948): 	at android.content.Intent.getStringExtra(Intent.java:5386)
E/Parcel  (  948): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1780)
E/Parcel  (  948): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1333)
E/Parcel  (  948): 	at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:5281)
E/Parcel  (  948): 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:257)
E/Parcel  (  948): 	at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:5079)
E/Parcel  (  948): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:262)
E/Parcel  (  948): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3172)
E/Parcel  (  948): 	at android.os.Binder.execTransact(Binder.java:446)
E/Parcel  (  948): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.finsky.billing.lightpurchase.PurchaseParams" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  (  948): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  (  948): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/Parcel  (  948): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/Parcel  (  948): 	... 18 more
E/Parcel  (  948): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.finsky.billing.lightpurchase.PurchaseParams
E/Parcel  (  948): 		at java.lang.Class.classForName(Native Method)
E/Parcel  (  948): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/Parcel  (  948): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/Parcel  (  948): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/Parcel  (  948): 		... 19 more
E/Parcel  (  948): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
V/ApplicationPolicy(  948): isApplicationStateBlocked userId 0 pkgname com.android.vending
```

I double checked the skus that I put in and they were correct.
I tried both test google play account and normal account.
Regular subscription works fine as always.

I tested on Samsung SM-N900L, Android 5.0,
Google Play Service 10.0.84 (238-137749526),
Google Play Store 7.3.07.K-all[0][PR].

If anything is needed, please let me know.

Thank you for reading and check for the issue, in advance.

**Comment by netomarin** [comment]
@songsingasong This method was added with version 5 of the in-app billing API (around February 2015).
But, is possible that your device haven't been updated.
To verify that the method is reported, send an isBillingSupported AIDL request.
Instead of using this method, we recommend that you use getBuyIntentExtraParams(), which provides additional functionality.

Hope I answered your question.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
