### ISSUE TITLE
Better error handling for devices with no Play Services

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-play-billing#50]
Hello,
currently, your app crashes when trying to buy gas on a device which has no Play Services (i.e. Genymotion emulator).  This is not user-friendly.  I think there should be a DialogFragment or a Toast message to tell the user that they are missing Play Services and that the action cannot be performed.  Instead, the following stacktrace currently occurs:
> FATAL EXCEPTION: main
                                                                                              Process: com.eazyigz.example.android.trivialdrivesample, PID: 1703
                                                                                              java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                                  at android.view.View$DeclaredOnClickListener.onClick(View.java:4697)
                                                                                                  at android.view.View.performClick(View.java:5609)
                                                                                                  at android.view.View$PerformClick.run(View.java:22259)
                                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at android.view.View$DeclaredOnClickListener.onClick(View.java:4692)
                                                                                                  at android.view.View.performClick(View.java:5609) 
                                                                                                  at android.view.View$PerformClick.run(View.java:22259) 
                                                                                                  at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                                               Caused by: java.lang.IllegalStateException: IAB helper is not set up. Can't perform operation: launchPurchaseFlow
                                                                                                  at com.example.android.trivialdrivesample.a.c.a(Unknown Source)
                                                                                                  at com.example.android.trivialdrivesample.a.c.a(Unknown Source)
                                                                                                  at com.example.android.trivialdrivesample.a.c.a(Unknown Source)
                                                                                                  at com.example.android.trivialdrivesample.MainActivity.onBuyGasButtonClicked(Unknown Source)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                  at android.view.View$DeclaredOnClickListener.onClick(View.java:4692) 
                                                                                                  at android.view.View.performClick(View.java:5609) 
                                                                                                  at android.view.View$PerformClick.run(View.java:22259) 
                                                                                                  at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by netomarin** [comment]
@IgorGanapolsky 
This happens because in-app transactions rely on Google Play app and Google Play Service, and this case that you faced on Genymotion should not happen on production.
And since this is a sample without intention to run out of this scope, this kind of validation haven't been done.

Thanks

**Comment by IgorGanapolsky** [comment]
@netomarin FYI: there are devices in the wild (especially in foreign countries) which don't have Play Services.  Having a safety check is prudent.
