### ISSUE TITLE
Crash on IabHelper.startSetup

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-play-billing#59]
I got this crash report recently. No idea why it occurs (reported on the play console) :

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lb.app_manager/com.lb.app_manager.activities.main_activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
  at android.app.ActivityThread.access$800(ActivityThread.java:178)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5624)
  at java.lang.reflect.Method.invoke(Method.java:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: java.lang.NullPointerException: 
  at com.lb.app_manager.utils.inapp_billing.utils.IabHelper.startSetup(IabHelper.java:272)

According to the code (I changed it a bit) , it crashes on this line:
        List<ResolveInfo> intentServices = mContext.getPackageManager().queryIntentServices(serviceIntent, 0);

This means that the queryIntentServices() returned null.
It seems you must check if it's null, according to the docs:
https://developer.android.com/reference/android/content/pm/PackageManager.html#queryIntentServices(android.content.Intent, int)

>  If there are no matching services, an empty list or null is returned.

Here are device stats, if this helps:
![image](https://user-images.githubusercontent.com/5357526/27262386-5875b612-545e-11e7-83df-a31405525377.png)

**Comment by AndroidDeveloperLB** [comment]
I think the correct code should be something like:

        final PackageManager packageManager = mContext.getPackageManager();
        final List<ResolveInfo> resolveInfos = packageManager.queryIntentServices(serviceIntent, 0);
        if (resolveInfos != null && !resolveInfos.isEmpty()) {
           ...

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

Please reopen if you still think this is an issue with the sample.

**Comment by AndroidDeveloperLB** [comment]
@pfmaggi The sample of "ClassiTexi" can't be used:
https://github.com/googlesamples/android-play-billing/issues/171
