### ISSUE TITLE
Play Billing Library: NPE on redeeming promo code

### ISSUE THREAD

**Issue by Zhelyazko** [googlesamples/android-play-billing#77]
I've been using the new Play billing library and so far it's working great.
When I generated some promo codes and decided to test them the app crashed with:

`
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.BaseBundle.get(java.lang.String)' on a null object reference
                                                          at com.android.billingclient.util.BillingHelper.getResponseCodeFromBundle(BillingHelper.java:71)
                                                          at com.android.billingclient.util.BillingHelper.getResponseCodeFromIntent(BillingHelper.java:64)
`

My app is free with in-app purchases. The error happened when trying to redeem a promo code for an in-app item.

Steps to reproduce:
1. Open the app for which you will redeem the promo code
2. As Promo code redeem option did not appear in the purchase flow, I opened Google Play app, went to "Redeem" menu and entered the promo code.
3. Tap the "Redeem" button.
4. My app crashed while in background.

I'm using `dp1` version of the library as that's the only one available.

Getting into the library's code where the crash happens is:
`
public static int getResponseCodeFromBundle(Bundle bundle, String tag) {
    Object responseCode = bundle.get(RESPONSE_CODE);
}
`

Clearly `Bundle` is null but I haven't checked if that's the expected result or there is some other issue causing the null `Bundle` object.

**Comment by stephanedupont** [comment]
@pfmaggi so where are we supposed to report Play Billing Library bugs?

**Comment by pfmaggi** [comment]
If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://b.corp.google.com/issues/new?component=311487&template=1014446

**Comment by stephanedupont** [comment]
@pfmaggi This links needs us to be logged with @google.com account.

**Comment by pfmaggi** [comment]
Sorry, the correct link is: https://issuetracker.google.com/issues/new?component=311487&template=1014446
